#!/bin/sh
#
# Auto-include ticket number "(JIRA-1234)" in commit message.
#
# The ticket number is extracted from the current branch name,
# assuming the name is in the format of "jira1234/my-feature".
#
# But if it's a "maint/" branch then keep it lowercased.

COMMIT_MSG_FILE=$1
COMMIT_SOURCE=$2
SHA1=$3

if [ -z "$COMMIT_SOURCE" ]; then
  content="$(cat $COMMIT_MSG_FILE)"
  # Turns "jira1234/my-feature" into "JIRA-1234"
  jira=$(git rev-parse --abbrev-ref HEAD | cut -f 1 -d / | tr a-z A-Z | sed 's/[0-9]/-&/')
  test "$jira" = "MAINT" && jira="maint"
  printf "($jira) \n" > "$COMMIT_MSG_FILE"
  echo "$content" >> "$COMMIT_MSG_FILE"
fi
