#!/bin/bash

symlink() {
    ln -s "$1" "$2"
    echo "Linked '$1' to '$2'"
}

maybe_symlink_file() {
    echo -n "  Backup & replace, Replace, View, Skip, Abort? (b/r/v/s/a) "
    read -r answer
    case $answer in
        b|B) mv "$2" "$2.bak"
             symlink "$1" "$2"
             ;;
        r|R) rm "$2"
             symlink "$1" "$2"
             ;;
        v|V) less "$2"
             maybe_symlink_file "$1" "$2"
             ;;
        s|S) # Do nothing
             echo "Skipped"
             ;;
        a|A) exit 0
             ;;
        *) echo "  Unknown selection"
           maybe_symlink_file "$1" "$2"
           ;;
    esac
}

maybe_symlink_directory() {
    echo -n "  Backup & replace, Replace, View, Skip, Abort? (b/r/v/s/a) "
    read -r answer
    case $answer in
        b|B) mv "$2" "$2.bak"
             symlink "$1" "$2"
             ;;
        r|R) rm -r "$2"
             symlink "$1" "$2"
             ;;
        v|V) ls "$2"
             maybe_symlink_directory "$1" "$2"
             ;;
        s|S) # Do nothing
             echo "Skipped"
             ;;
        a|A) exit 0
             ;;
        *) echo "  Unknown selection"
           maybe_symlink_directory "$1" "$2"
           ;;
    esac
}

maybe_symlink_symlink() {
    echo -n "  Replace, View, Skip, Abort? (r/v/s/a) "
    read -r answer
    case $answer in
        r|R) rm "$2"
             symlink "$1" "$2"
             ;;
        v|V) ls -l "$2"
             maybe_symlink_symlink "$1" "$2"
             ;;
        s|S) # Do nothing
             echo "Skipped"
             ;;
        a|A) exit 0
             ;;
        *) echo "  Unknown selection"
           maybe_symlink_symlink "$1" "$2"
           ;;
    esac
}

maybe_symlink() {
    echo -n "Link '$1' to '$2'? (y/n) "
    read -r answer
    case $answer in
        y) if [ -h "$2" ]; then
               echo "'$2' is already a SYMLINK."
               maybe_symlink_symlink "$1" "$2"
           elif [ -f "$2" ]; then
               echo "'$2' is already a FILE."
               maybe_symlink_file "$1" "$2"
           elif [ -d "$2" ]; then
               echo "'$2' is already a DIRECTORY."
               maybe_symlink_directory "$1" "$2"
           else
               symlink "$1" "$2"
           fi
           echo # Blank line for readability
           ;;
        n) echo "Skipped"
           echo # Blank line for readability
           ;;
        *) echo "  Unknown selection"
           maybe_symlink "$1" "$2"
           ;;
    esac
}

link_home() {
    target="$2"
    if [ -z "$target" ]; then
        target=".$(basename "$1")"
    fi
    maybe_symlink "$PWD/$1" "$HOME/$target"
}

# Scripts directory
link_home bin bin

# Bash
link_home bash/bashrc
link_home bash/bash_profile

# Git
link_home git/gitconfig
link_home git/gitignore
case $(uname -s) in
    Linux) link_home git/gitconfig.linux .gitconfig.os ;;
    Darwin) link_home git/gitconfig.macos .gitconfig.os ;;
    *) echo "Unknown OS; skipping .gitconfig.os" ;;
esac

# Emacs
link_home emacs/init.el .emacs.d/init.el
link_home emacs/zile

# Vim
link_home vim/vimrc

# Miscellaneous
link_home bash/inputrc
link_home misc/hushlogin
link_home misc/shellcheckrc
link_home misc/rgignore
