#!/bin/bash

function symlink {
    ln -s "$1" "$2"
    echo "Linked '$1' to '$2'"
}

function maybe_symlink_file {
    echo -n "  Backup & replace, Replace, View, Skip, Abort? (b/r/v/s/a) "
    read answer
    case $answer in
        b|B) mv "$2" "$2.bak"
             symlink "$1" "$2"
             ;;
        r|R) rm "$2"
             symlink "$1" "$2"
             ;;
        v|V) less "$2"
             maybe_symlink_file "$1" "$2"
             ;;
        s|S) # Do nothing
             ;;
        a|A) exit 0
             ;;
        *) echo "  Unknown selection"
           maybe_symlink_file "$1" "$2"
           ;;
    esac
}

function maybe_symlink_directory {
    echo -n "  Backup & replace, Replace, View, Skip, Abort? (b/r/v/s/a) "
    read answer
    case $answer in
        b|B) mv "$2" "$2.bak"
             symlink "$1" "$2"
             ;;
        r|R) rm -r "$2"
             symlink "$1" "$2"
             ;;
        v|V) ls "$2"
             maybe_symlink_directory "$1" "$2"
             ;;
        s|S) # Do nothing
             ;;
        a|A) exit 0
             ;;
        *) echo "  Unknown selection"
           maybe_symlink_directory "$1" "$2"
           ;;
    esac
}

function maybe_symlink_symlink {
    echo -n "  Replace, View, Skip, Abort? (r/v/s/a) "
    read answer
    case $answer in
        r|R) rm "$2"
             symlink "$1" "$2"
             ;;
        v|V) ls -l "$2"
             maybe_symlink_symlink "$1" "$2"
             ;;
        s|S) # Do nothing
             ;;
        a|A) exit 0
             ;;
        *) echo "  Unknown selection"
           maybe_symlink_symlink "$1" "$2"
           ;;
    esac
}

function maybe_symlink {
    if [ -h "$2" ]; then
        echo "'$2' is already a SYMLINK."
        maybe_symlink_symlink "$1" "$2"
    elif [ -f "$2" ]; then
        echo "'$2' is already a FILE."
        maybe_symlink_file "$1" "$2"
    elif [ -d "$2" ]; then
        echo "'$2' is already a DIRECTORY."
        maybe_symlink_directory "$1" "$2"
    else
        symlink "$1" "$2"
    fi
    echo # Blank line for readability
}

function link_dotfile {
    maybe_symlink "$PWD/$1" "$HOME/.$(basename $1)"
}

maybe_symlink $PWD/bin $HOME/bin
link_dotfile bash/bash_profile
link_dotfile bash/bashrc
link_dotfile zsh/zshenv
link_dotfile zsh/zshrc
link_dotfile git/gitconfig
link_dotfile git/gitignore
link_dotfile vim/vimrc
link_dotfile vim/gvimrc
link_dotfile emacs/spacemacs
link_dotfile misc/tmux.conf
link_dotfile misc/gemfile
