#+TITLE: Dotfiles

My configuration files for Bash, Vim, Emacs, OSX, etc.

* Contents

 Most things are organized in directories named after the tool.
 For example, Bash files like ~.bashrc~ and ~.bash_profile~ are in =bash/=.

 However, there are a couple special directories that don't follow this pattern:

 - =bin/=: Executables; directory symlinked into home directory and added to =$PATH=
 - =misc/=: Miscellaneous things which don't yet have their own home directory

* Installation

 Run [[./install][./install]] from the root repository directory.

 It will symlink files into your home directory. If there are any existing
 files or directories, the installer will ask you what you want to do with
 it. It will not overwrite or destroy anything without asking you first.

 #+BEGIN_SRC sh
   $ git clone https://github.com/nwolfe/dotfiles ~/.dotfiles
   $ cd ~/.dotfiles
   $ ./install
 #+END_SRC

** Mac OS

 Configuration is in the [[./misc/osx][misc/osx]] file. You must source it manually.
