#!/usr/bin/env bash
#
# Composes multiple hooks into a single hook file for Git.
#
# LABEL: pre-commit-composite-file

# List of actual hooks to execute
hooks="$(dirname $0)"/pre-commit-hooks

# Exit early if there are no hooks to run
! test -s "$hooks" && exit

EXITCODE=0

# A hook that passes should have no output. If there is output,
# echo it and set the exit code to fail, but continue running
# the remaining hooks.
while read hook; do
    out="$($hook)"
    if [ -n "$out" ]; then
        echo "> $hook"
        echo "$out"
        echo
        EXITCODE=1
    fi
done < "$hooks"

exit $EXITCODE
