#!/bin/sh

# Navigation
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias p='cd $PUPPETLABS'
alias pdb='cd $PUPPETLABS/puppetdb'
alias tk='cd $PUPPETLABS/trapperkeeper'
alias jvm='cd $PUPPETLABS/jvm-puppet'
alias ca='cd $PUPPETLABS/jvm-certificate-authority'

# Verify destruction
alias rm='rm -iv' # Verbose, print removed files
alias mv='mv -i'
alias cp='cp -i'

# List directory contents
# -h  Human-readable file sizes
# -G  Colored output
# -F  Append special character denoting file type
# -o  Long format, omit owner
# -g  Long format, omit group
alias ls='ls -hG'
alias ll='ls -og'
alias la='ls -A'
alias l1='ls -1'

# Shortcuts
alias e='eval $EDITOR'
alias tmux='tmux -2' # Ensure 256 colors
alias sshcent6='ssh root@pe-centos6'
alias sshdeb6='ssh root@pe-debian6'
