#!/bin/bash

# Completes: <command> [master|server|agent] [v3|v4]
_component-version() {
    _arguments "1: :(master server agent)"
    _arguments "2: :(v3 v4)"
}

# Completes: <command> [v3|v4]
_version() {
    _arguments "1: :(v3 v4)"
}
