#!/bin/sh

# List directory contents after cd
# This is a special hook function called by zsh
function chpwd() {
  ls
}

# Create executable shell script with hash-bang line
function mkscript() {
  if [ -e $1 ]; then
      echo "ERROR: $1 already exists" 1>&2
      return 1
  fi

  echo "#!/bin/sh" > $1
  chmod 777 $1
  return 0
}

# Create source file with hash-bang line
function mksource() {
  if [ -e $1 ]; then
    echo "ERROR: $1 already exists" 1>&2
    return 1
  fi

  echo "#!/bin/sh" > $1
  return 0
}
