#!/bin/sh
# General-purpose functions for all sorts of things

# List directory contents after cd
# This is a special hook function called by zsh
function chpwd() {
  ls
}

# Create executable shell script with hash-bang line
#
# Usage:
#
#   % mkscript run.sh
function mkscript() {
  if [ -e $1 ]; then
      echo "ERROR: $1 already exists" 1>&2
      return 1
  fi

  echo "#!/bin/sh" > $1
  chmod 777 $1
  return 0
}

# Create source file with hash-bang line
#
# Usage:
#
#   % mksource aliases
function mksource() {
  if [ -e $1 ]; then
    echo "ERROR: $1 already exists" 1>&2
    return 1
  fi

  echo "#!/bin/sh" > $1
  return 0
}
