#!/bin/sh

export PUPPETLABS=/Users/nwolfe/workspace/puppetlabs
CONF_DIR=$PUPPETLABS/conf
DEFAULT_PUPPET_TESTDIR=$CONF_DIR/puppet

function puppetEnv() {
  local PUPPET_HOME=$PUPPETLABS/puppet
  local FACTER_HOME=$PUPPETLABS/facter
  export RUBYLIB=$PUPPET_HOME/lib:$FACTER_HOME/lib
  export PATH=$PATH:$PUPPET_HOME/bin:$FACTER_HOME/bin
}

function runMaster() {
  local TESTDIR=${1:-$DEFAULT_PUPPET_TESTDIR}
  local COMMAND="puppet master --autosign=true --no-daemonize --debug --verbose --confdir=$TESTDIR/master/conf --vardir=$TESTDIR/master/var --certname localhost"
  echo $COMMAND
  echo -n $COMMAND | pbcopy
}

function runAgent() {
  local TESTDIR=${1:-$DEFAULT_PUPPET_TESTDIR}
  local COMMAND="puppet agent --no-daemonize --debug --trace --verbose --confdir=$TESTDIR/agent/conf --vardir=$TESTDIR/agent/var --server localhost --onetime --certname localhost-puppetdb"
  echo $COMMAND
  echo -n $COMMAND | pbcopy
}

function puppetdbEnv() {
  export RUBYLIB=$RUBYLIB:$PUPPETLABS/puppetdb/puppet/lib
}

# Set environment variables to make PuppetDB use PostgreSQL instead of HSQL when running 'lein test'
function puppetdbPostgresEnv() {
  export PUPPETDB_DBTYPE=postgres
  export PUPPETDB_DBSUBNAME=puppetdb_tests
  export PUPPETDB_DBUSER=puppetdb
  export PUPPETDB_DBPASSWORD=puppetdb
}

function runPuppetdb() {
  cd $PUPPETLABS/puppetdb
  local COMMAND="lein trampoline run services --config $CONF_DIR/puppetdb/config.ini"
  echo $COMMAND
  echo -n $COMMAND | pbcopy
}

function runPuppetdbAcceptanceTests() {
  cd $PUPPETLABS/puppet-acceptance
  rvm use 1.8.7
  ./runtest.sh $PUPPETLABS/puppetdb/acceptance/tests
}

# Issue curl query to PuppetDB
function query() {
  local FLAGS=-G
  if [ "$1" = "-v" ]; then
    FLAGS+=v
    shift
  fi
  local ENDPOINT=$1; shift
  local PARAMS="http://localhost:8080/v3/$ENDPOINT "
  for param
  do
    PARAMS+="--data-urlencode '$param' "
  done

  eval curl $FLAGS $PARAMS
}

function enable-no-password-login-on() {
  cat ~/.ssh/id_rsa.pub | ssh root@$1 "cat >> ~/.ssh/authorized_keys"
}
