#!/bin/sh
# Simple tool for remembering (writing) notes

NOTES_HOME=$HOME/.dotfiles/notes
DEFAULT_NOTEFILE=notes

# Commit the notefile with a default message.
# $1 = absolute path to notefile (e.g. /users/foo/bar)
# $2 = notefile name (e.g. bar)
__save_changes() {
  git add $1
  git commit -m "$2 notes" $1 > /dev/null
  return 0
}

# Returns the full path to $1 notefile
__absolute_path() {
  echo $NOTES_HOME/${1}.txt
}

# Edit the $1 notefile in your favorite editor
__edit_notefile() {
  notefile=${1//:/}
  filepath=$(__absolute_path $notefile)
  $VISUAL $filepath
  __save_changes $filepath $notefile
}

# Edit the default notefile in your favorite editor
__edit_default() {
  __edit_notefile $DEFAULT_NOTEFILE
}

# Write (append) the note to the $1 notefile
__write_note() {
  if [ ${1:(-1)} = ":" ]; then
    notefile=${1//:/}
    shift
  else
    notefile=$DEFAULT_NOTEFILE
  fi
  filepath=$(__absolute_path $notefile)
  echo $* >> $filepath
  __save_changes $filepath $notefile
}

# Remember something!
#
# Examples
#   $ rem This is cool!
#   $ rem "This is cool!"
#   > echo "This is cool!" >> ~/notes/notes.txt
#
#   $ rem foo: So is this!
#   $ rem foo: "So is this!"
#   > echo "So is this!" >> ~/notes/foo.txt
#
#   $ rem
#   > $VISUAL ~/notes/notes.txt
#
#   $ rem foo
#   $ rem foo:
#   > $VISUAL ~/notes/foo.txt
rem() {
  case $# in
    0) __edit_default ;;
    1) __edit_notefile $1 ;;
    *) __write_note $* ;;
  esac
}
