#!/usr/bin/env bash
#
# Check for System.[out,err].print* calls.

output=$(git diff --exit-code --name-only --staged --diff-filter=d \
    | grep "$*.java$" | xargs grep -nH "System\.out\|err\.print.*")

if [ -z "$output" ]; then
    exit 0
else
    echo "Found println's"
    echo
    echo "$output"
    exit 1
fi
