#!/usr/bin/env bash
#
# Check for "TODO(nwolfe)" comments.

output=$(git diff --exit-code --name-only --staged --diff-filter=d \
    | xargs grep -nH ".*TODO(nwolfe).*")

if [ -z "$output" ]; then
    exit 0
else
    echo "Found TODO's"
    echo
    echo "$output"
    exit 1
fi
