#!/usr/bin/env bash

# Install CLI and GUI software using Homebrew.
#
# Run periodically to update/upgrade Homebrew and packages.
#
# See: https://github.com/mathiasbynens/dotfiles/blob/master/brew.sh

# Make sure we’re using the latest Homebrew
brew update

# Packages (CLIs)
brew tap d12frosted/emacs-plus
brew install emacs-plus@27
if ! test -h /Applications/Emacs.app; then
    ln -s /usr/local/opt/emacs-plus@27/Emacs.app /Applications
fi

brew install bash
brew install bash-completion2
if ! grep -Fq '/usr/local/bin/bash' /etc/shells; then
    echo '/usr/local/bin/bash' | sudo tee -a /etc/shells
    chsh -s /usr/local/bin/bash
fi

brew install git
brew install ripgrep
brew install shellcheck
brew install tree
brew install jq
brew install zile
brew install bat
brew install fzf
brew install htop

# Casks (GUIs)
brew cask install iterm2
brew cask install firefox
brew cask install rectangle
brew cask install aerial
brew cask install caffeine

# Upgrade any other installed formulae.
# Do this last so it's easier to notice if anything is
# upgraded and should be explicitly installed above
brew upgrade
brew upgrade --cask

# Remove outdated versions from the cellar
brew cleanup

# Try and catch issues early
brew doctor
