#!/usr/bin/env bash

# Install command-line tools using Homebrew.
#
# Run periodically to update/upgrade Homebrew and packages.
#
# See: https://github.com/mathiasbynens/dotfiles/blob/master/brew.sh

# Make sure we’re using the latest Homebrew
brew update

# Upgrade any already-installed formulae
brew upgrade
brew cask upgrade

brew cask install rectangle
brew cask install aerial
brew cask install caffeine

# Shell -- install Bash 4 and set it as default shell
brew install bash
brew install bash-completion2
if ! grep -Fq '/usr/local/bin/bash' /etc/shells; then
    echo '/usr/local/bin/bash' | sudo tee -a /etc/shells
    chsh -s /usr/local/bin/bash
fi

brew install ripgrep
brew install gnu-tar
brew install gnutls
brew install coreutils
brew install fd
brew install markdown
brew install shellcheck
brew install tree
brew install jq
brew install gnu-sed   # install-pre-commit-hook script
brew install zile
brew install bat
brew install fzf
brew install htop

# Remove outdated versions from the cellar
brew cleanup

# Try and catch issues early
brew doctor
