# -*- mode: sh -*-

# Source .seacrest things if they exist
if [ -d $HOME/.seacrest ]; then
    source $HOME/.seacrest/shell/sources/env
fi

# Set Emacs as default system editors.
#
# Use full path to executable for command-line git to work properly,
# otherwise it finds the built-in version that doesn't support the
# various flags used below.
#
#   --tty                    Open frame in current terminal,
#                            not in last active frame.
#
#   --alternate-editor=''    Start daemon server if there isn't one.
export EDITOR="/usr/local/bin/emacsclient --tty --alternate-editor=''"

export DOTFILES=$HOME/.dotfiles
export NOTES=$HOME/org/notes
export PATH=/usr/local/bin:/usr/local/sbin:$HOME/bin:$PATH
export PUPPETLABS=$HOME/workspace/puppetlabs
export PUPPETLABS_CONF=$PUPPETLABS/conf
export VISUAL=$EDITOR

export RBENV_ROOT=/usr/local/opt/rbenv
if which rbenv > /dev/null; then
    eval "$(rbenv init -)"
fi

export PYENV_ROOT=/usr/local/var/pyenv
if which pyenv > /dev/null; then
    eval "$(pyenv init -)"
fi
