# -*- mode: sh -*-

# Source things like aliases, functions, etc.
# Environment variables are defined in ~/.bash_profile.
source $DOTFILES/sources/aliases
source $DOTFILES/sources/completions
source $DOTFILES/sources/functions
