# -*- mode: sh -*-
export TERM=xterm-256color
export DOTFILES=$HOME/.dotfiles

# Source .seacrest things if they exist
if [ -d $HOME/.seacrest ]; then
    for sourcefile in $HOME/.seacrest/shell/sources/*; do
        source $sourcefile
    done
fi

# Source things like env, aliases, functions, etc.
for sourcefile in $DOTFILES/sources/*; do
    source $sourcefile
done
