# -*- mode: sh -*-
# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME=steeef
#ZSH_THEME=avit
#ZSH_THEME=goodsam
#ZSH_THEME=nanotech
#ZSH_THEME=juanghurtado
#ZSH_THEME=wezm
#ZSH_THEME=nicoulaj
#ZSH_THEME=blinks
#ZSH_THEME=sorin

# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

# Set to this to use case-sensitive completion
# CASE_SENSITIVE="true"

# Comment this out to disable bi-weekly auto-update checks
# DISABLE_AUTO_UPDATE="true"

# Uncomment to change how often before auto-updates occur? (in days)
# export UPDATE_ZSH_DAYS=13

# Uncomment following line if you want to disable colors in ls
# DISABLE_LS_COLORS="true"

# Uncomment following line if you want to disable autosetting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment following line if you want to disable command autocorrection
# DISABLE_CORRECTION="true"

# Uncomment following line if you want red dots to be displayed while waiting for completion
COMPLETION_WAITING_DOTS="true"

# Uncomment following line if you want to disable marking untracked files under
# VCS as dirty. This makes repository status check for large repositories much,
# much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Full list of plugins: https://github.com/robbyrussell/oh-my-zsh/wiki/Plugins
plugins=(brew osx lein colored-man jsontools
         gitfast
         ruby rake rbenv gem)

source $ZSH/oh-my-zsh.sh

################################################################################

# Defer to .bashrc for most configuration
source $HOME/.bashrc

# Automatically do an `ls` after `cd`-ing to a directory
chpwd() {
    ls
}

## Auto-completion support
## * Standalone completion files from $DOTFILES/completion (added to zsh FPATH)
## * Completion functions from $DOTFILES/sources/completions (sourced manually)
## See http://askql.wordpress.com/2011/01/11/zsh-writing-own-completion

# Add custom completion scripts for commands that warrant a dedicated file
fpath=($DOTFILES/completion $fpath)

# Initialize compsys
autoload -U compinit
compinit

# Set reusable completion functions on various commands.
# Completion functions defined in $DOTFILES/sources/completions
compdef _component-version puppet-cli-env puppet-ssl-env remove-ssl pconf
compdef _version run-agent run-master run-server

# Show completion menu when number of options is at least 2
zstyle ':completion:*' menu select=2
