# -*- mode: sh -*-

# Source .seacrest things if they exist
if [ -d $HOME/.seacrest ]; then
    source $HOME/.seacrest/shell/sources/env
fi

# Source .bashrc if it exists
if [ -f $HOME/.bashrc ]; then
    source $HOME/.bashrc
fi

export DOTFILES=$HOME/.dotfiles
export EDITOR=vim
export VISUAL=$EDITOR
export DEV_ROOT=$HOME/ws/puppet/
export JAVA_HOME=$(/usr/libexec/java_home)

# Brighten the blue color of directories in ls output
export LSCOLORS=Exfxcxdxbxegedabagacad

# Overwrite system Ruby with Homebrew version
export PATH=/usr/local/opt/ruby/bin:$PATH
# Homebrew recommended
export PATH=/usr/local/sbin:$PATH
# Personal scripts from dotfiles
export PATH=$HOME/bin:$PATH
