# -*- mode: sh -*-

# Navigation
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
# alias pp='cd $PUPPETLABS'

# Verify destruction
alias rm='rm -i'
alias mv='mv -i'
alias cp='cp -i'

# List directory contents
# -h  Human-readable file sizes
# -G  Colored output
# -F  Append special character denoting file type
# -A  Show hidden entries, but hide . and ..
# -1  One entry per line
alias ls='ls -FG'
alias ll='ls -hl'
alias la='ls -A'

# Shortcuts
# alias remove-ds-stores='find . -name ".DS_Store" -type f -delete'
alias gb='git branch'
alias gcm='git checkout master'
alias gco='git checkout'
alias gd='git diff'
alias gds='git diff --staged'
alias gst='git status'
alias dc='docker-compose'

# Emacs
#alias emacs-server='emacs --daemon'
#alias emacs-server-kill='emacsclient -e "(spacemacs/save-buffers-kill-emacs)"'
alias e='emacs -nw'
alias est='emacs -nw -f magit-status'
