# -*- mode: sh -*-

# Source .seacrest things if they exist
if [ -d $HOME/.seacrest ]; then
    source $HOME/.seacrest/shell/sources/env
fi

# Source .bashrc if it exists
if [ -f $HOME/.bashrc ]; then
    source $HOME/.bashrc
fi

export DOTFILES=$HOME/.dotfiles
export EDITOR=vim
export VISUAL=$EDITOR
export PATH=$HOME/bin:$PATH
export DEV_ROOT=$HOME/ws/puppet/
export JAVA_HOME=$(/usr/libexec/java_home)

# Brighten the blue color of directories in ls output
export LSCOLORS=Exfxcxdxbxegedabagacad
