# -*- mode: sh -*-

# Source .seacrest things if they exist
if [ -d $HOME/.seacrest ]; then
    source $HOME/.seacrest/shell/sources/env
fi

# Source .bashrc if it exists
if [ -f $HOME/.bashrc ]; then
    source $HOME/.bashrc
fi

export PD_BAZEL_GENFILES=/home/nwolfe/workspace/puppetlabs/cloud-discovery/bazel-genfiles

export EDITOR=vim
export DOTFILES=$HOME/.dotfiles
# export IPADDRESS=$(ifconfig en0 | grep inet | awk '{print $2}')
export PUPPETLABS=$HOME/workspace/puppetlabs
export VISUAL=$EDITOR
export GOPATH=$HOME/workspace/go
export PATH=$HOME/bin:$GOPATH/bin:$PATH
export PDDIR=$PD_BAZEL_GENFILES/workstation/bin/dev-local/linux-amd64/.puppet-discovery
