#!/usr/bin/env bash
#
# Run the Google Java Format tool over changed .java files.
#
# Creates a follow-up commit with formatting changes.
#
# See https://github.com/google/google-java-format

jar=~/Downloads/google-java-format-1.7-all-deps.jar

# Get paths of changed .java files in previous commit.
# Ignore files that were deleted.
changed_java_files=$(git diff HEAD~1 --name-only --diff-filter=d \
    | grep "$*.java$")

# Exit early if there's no java files to format
[ -z "$changed_java_files" ] && exit

# Run formatter and make changes directly to files
java -jar "$jar" --replace --set-exit-if-changed $changed_java_files

# Auto-commit formatting changes
# Disable all hooks during this commit so we don't recurse
if [ $? -ne 0 ]; then
    git add $changed_java_files
    git -c core.hooksPath= commit --message "(maint) Apply $(basename $jar)"
fi
